import 'dart:io';
import 'dart:convert';

void main() async {
  print('Starting SEO static pages generation...');

  final webDir = Directory('web');
  if (!webDir.existsSync()) {
    print('Error: web directory not found.');
    exit(1);
  }

  final indexFile = File('web/index.html');
  String template = await indexFile.readAsString();

  final outDir = Directory('web/use-cases');
  if (!outDir.existsSync()) {
    outDir.createSync(recursive: true);
  }

  final pages = [
    {
      'id': 'pdf-student-essay-detector',
      'lang': 'en',
      'title': 'PDF Student Essay AI Detector',
      'desc': 'Analyze PDF student essays for AI content locally without uploading to the cloud. Protect student privacy with TruthLens.',
      'h1': 'PDF Student Essay AI Detector',
      'lead': 'Protect student privacy by scanning PDF essays for AI content completely on your device. No cloud uploads.',
      'faq': [
        {'q': 'Does TruthLens upload student essays?', 'a': 'No. TruthLens is a local-first AI detector. All analysis happens on your device.'},
        {'q': 'Can it detect AI in PDF files?', 'a': 'Yes, TruthLens extracts text from PDFs and analyzes it using multi-engine signals.'}
      ]
    },
    {
      'id': 'docx-contract-ai-checker',
      'lang': 'en',
      'title': 'DOCX Contract AI Checker',
      'desc': 'Verify if a Word (DOCX) contract or legal document was generated by AI. Check editing history forensics locally.',
      'h1': 'DOCX Contract AI Checker',
      'lead': 'Scan legal contracts for AI generation markers and editing history anomalies without compromising confidentiality.',
      'faq': [
        {'q': 'Is my contract safe?', 'a': 'Yes, all processing is done locally in your browser. No data leaves your machine.'},
        {'q': 'Why check DOCX history?', 'a': 'Original DOCX files preserve drafting history, which provides strong evidence of human vs AI writing.'}
      ]
    },
    {
      'id': 'pdf-student-essay-detector-zh',
      'lang': 'zh-Hant',
      'title': 'PDF 學生論文 AI 檢測器',
      'desc': '在本地端檢測 PDF 學生報告與論文是否由 AI 生成，無需上傳雲端，保護學術隱私。',
      'h1': 'PDF 學生論文 AI 檢測器',
      'lead': '完全在您的裝置上掃描 PDF 論文的 AI 內容，保護學生隱私，不上傳任何資料。',
      'faq': [
        {'q': 'TruthLens 會上傳學生的論文嗎？', 'a': '不會。TruthLens 是本地優先的 AI 檢測器，所有分析都在您的裝置上進行。'},
        {'q': '支援 PDF 檔案嗎？', 'a': '是的，TruthLens 支援擷取 PDF 文字並進行多引擎交叉分析。'}
      ]
    }
  ];

  List<String> generatedUrls = [];

  for (final page in pages) {
    String pageHtml = template;
    
    // Replace title
    pageHtml = pageHtml.replaceFirst(
        RegExp(r'<title>.*?</title>'), '<title>${page['title']} | TruthLens</title>');
    
    // Replace description
    pageHtml = pageHtml.replaceFirst(
        RegExp(r'<meta name="description" content="[^"]*">'),
        '<meta name="description" content="${page['desc']}">');

    // Generate FAQ Schema
    String faqSchema = '';
    if (page['faq'] != null) {
      final faqs = page['faq'] as List<Map<String, String>>;
      final mainEntity = faqs.map((f) => {
        "@type": "Question",
        "name": f['q'],
        "acceptedAnswer": {
          "@type": "Answer",
          "text": f['a']
        }
      }).toList();

      final schemaObj = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": mainEntity
      };
      faqSchema = '<script type="application/ld+json">\n${jsonEncode(schemaObj)}\n</script>\n';
    }

    // Insert FAQ schema before </head>
    pageHtml = pageHtml.replaceFirst('</head>', '$faqSchema</head>');

    // Replace H1
    pageHtml = pageHtml.replaceFirst(
        RegExp(r'<h1 id="seo-title"[^>]*>.*?</h1>'), 
        '<h1 id="seo-title" class="seo-shell__brand">${page['h1']}</h1>');

    // Replace Lead
    pageHtml = pageHtml.replaceFirst(
        RegExp(r'<p class="seo-shell__lead" data-home-lead>.*?</p>', dotAll: true), 
        '<p class="seo-shell__lead" data-home-lead>${page['lead']}</p>');

    final filePath = 'web/use-cases/${page['id']}.html';
    File(filePath).writeAsStringSync(pageHtml);
    print('Generated: $filePath');
    
    generatedUrls.add('https://truth-lens-roan-three.vercel.app/use-cases/${page['id']}');
  }

  final sitemapFile = File('web/sitemap.xml');
  String sitemapXml = '';
  if (sitemapFile.existsSync()) {
    sitemapXml = sitemapFile.readAsStringSync();
    
    sitemapXml = sitemapXml.replaceAll('</urlset>', '');
    
    final today = DateTime.now().toIso8601String().split('T').first;
    for (final url in generatedUrls) {
      if (!sitemapXml.contains(url)) {
        sitemapXml += '''
  <url>
    <loc>$url</loc>
    <lastmod>$today</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
''';
      }
    }
    sitemapXml += '</urlset>\\n';
    sitemapFile.writeAsStringSync(sitemapXml);
    print('Updated web/sitemap.xml');
  }

  String directoryHtml = '''
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Sitemap Directory | TruthLens</title>
  <meta name="robots" content="noindex, follow">
  <style>
    body { font-family: sans-serif; padding: 2rem; max-width: 800px; margin: 0 auto; line-height: 1.6; }
    ul { list-style: none; padding: 0; }
    li { margin-bottom: 10px; }
    a { color: #31558f; text-decoration: none; }
    a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <h1>TruthLens Directory</h1>
  <ul>
''';
  for (final page in pages) {
    directoryHtml += '    <li><a href="/use-cases/${page['id']}">${page['title']}</a></li>\n';
  }
  directoryHtml += '''
  </ul>
</body>
</html>
''';
  File('web/sitemap_directory.html').writeAsStringSync(directoryHtml);
  print('Generated web/sitemap_directory.html');

  print('Done.');
}
